### ISSUE TITLE
Installing swift 5.6 fails with gpg error

### ISSUE THREAD

**Issue by Andrewangeta** [swift-actions/setup-swift#520]
**Describe the bug**
When specifying swift 5.6 as the target swift version, there is a gpg error where it cannot continue
Yaml being used:
```yaml
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift-version: ['5.6', '5.7', '5.7.1', '5.7.2']
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    steps:
     - name: Check out  
       uses: actions/checkout@v3
        
     - name: Install Swift
       uses: swift-actions/setup-swift@v1
       with:
         swift-version: ${{ matrix.swift-version }}
        
     - name: Start MongoDB
       uses: supercharge/mongodb-github-action@1.8.0
       with:
         mongodb-version: ${{ matrix.mongodb-version }}
         mongodb-replica-set: mk-rs
        
     - name: Run tests
       run: swift test
```

<img width="1244" alt="Screenshot 2023-01-07 at 1 54 16 PM" src="https://user-images.githubusercontent.com/12012815/211166339-0decdb9a-ad4b-4e8b-965f-92f617b4c66f.png">

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): swift-actions/setup-swift@v1
 - Platform (`runs-on`): ubuntu-latest
 - Swift version (`swift-version`): 5.6
