### ISSUE TITLE
swift-actions/setup-swift is using 10GB of the 17G storage space available in a macos-runner

### ISSUE THREAD

**Issue by Aaron-Ritter** [swift-actions/setup-swift#682]
**Describe the bug**
swift-actions/setup-swift is using 10GB of the 17G storage space available in a macos-runner

![image](https://github.com/user-attachments/assets/9929388f-1fa4-4050-8b5a-b0066eb14ac5)

**Workflow configuration (please complete the following information):**

```
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.10.1"]
        os: [macos-latest]
        include:
          - language: swift
            build-mode: manual
        # CodeQL supports the following values keywords for 'language': 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
        # Use `c-cpp` to analyze code written in C, C++ or both
        # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
        # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
        # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis,
        # see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
        # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how
        # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
    steps:
      - name: Check Disk Space 1
        run: df -h

      - name: Initialize latest xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Check Disk Space 2
        run: df -h

      - name: Initialize Swift
        uses: swift-actions/setup-swift@v2.1.0
        with:
          swift-version: ${{ matrix.swift }}

      - name: Check Disk Space 3
        run: df -h

      - name: Get swift version
        run: swift --version

      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Check Disk Space 4
        run: df -h
```
