### ISSUE TITLE
"no valid OpenPGP data found" when running gpg --import step

### ISSUE THREAD

**Issue by dextero** [swift-actions/setup-swift#690]
**Describe the bug**
`gpg --import` failed with "no valid OpenPGP data found":

```
/usr/bin/gpg --import /home/runner/work/_temp/626eeca3-6ebc-44ca-b365-64f3c60c706c
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:319[5](https://github.com/google/flatbuffers/actions/runs/13121741713/job/36610170747?pr=8512#step:3:6):25)
    at ExecState.CheckComplete (/home/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:3178:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:3072:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:1[6](https://github.com/google/flatbuffers/actions/runs/13121741713/job/36610170747?pr=8512#step:3:7))
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

Full log: https://github.com/google/flatbuffers/actions/runs/13121741713/job/36610170747?pr=8512
Workflow config: https://github.com/google/flatbuffers/blob/0312061985dbaaf6b068006383946ac6095f5b63/.github/workflows/build.yml#L494

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): `swift-actions/setup-swift@v2`
 - Platform (`runs-on`): `ubuntu-22.04`
 - Swift version (`swift-version`): `5.10`

**Comment by lemo-nade-room** [comment]
I also encountered the same issue today (2025/02/04) even though nothing has changed—the workflow was passing on 2025/02/03.

Here is the error I observed:

```
Run swift-actions/setup-swift@v2
  with:
    swift-version: 6.0
/usr/bin/gpg --import /home/runner/work/_temp/81984d52-2a7c-41ba-87dd-6de568b67a0e
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:3195:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:3178:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/swift-actions/setup-swift/v2/dist/index.js:3072:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

My CI run can be found here: [CI URL](https://github.com/lemo-nade-room/event-store-adaptor-swift/actions/runs/13125655108/job/36622194461)

The GitHub Actions workflow configuration I am using is as follows:

```yaml
build:
  timeout-minutes: 10
  runs-on: ubuntu-latest
  needs: lint
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: swift-build-package-resolved-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Package.resolved') }}
        path: .build
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - run: swift build
```

Any guidance on how to resolve this issue would be greatly appreciated. Thank you!
