### ISSUE TITLE
Support Swift 6.1

### ISSUE THREAD

**Issue by IT-Guy007** [swift-actions/setup-swift#706]
**Describe the bug**
Run swift-actions/setup-swift@v2.2.0
  with:
    swift-version: 6.1
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
Version "6.1" is not available
Stacktrace:
Error: Version "6.1" is not available
    at Object.verify (/Users/runner/work/_actions/swift-actions/setup-swift/v2.2.0/dist/index.js:576:15)
    at run (/Users/runner/work/_actions/swift-actions/setup-swift/v2.2.0/dist/index.js:329:32)

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): [e.g. swift-actions/setup-swift@v2.20]
 - Platform (`runs-on`): [e.g. macos-latest]
 - Swift version (`swift-version`): [e.g. 6.1]

Action:
```yaml
name: Test package

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }} - ${{ matrix.config }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.1"]
        config: [release, debug]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: ${{ matrix.swift }}

      - uses: actions/checkout@v4

      - name: Configure GitHub credentials
        run: |
          echo "https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Run tests
        run: swift test -c ${{ matrix.config }}
```
