### ISSUE TITLE
Swift 6.1 isn't available on Windows

### ISSUE THREAD

**Issue by shial4** [swift-actions/setup-swift#709]
Describe the bug
"Version "6.1.0" is not available"

```
name: Build TradeWithIt

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        swift: ["6.1.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.3.0
        with:
          swift-version: ${{ matrix.swift }}

      - name: Get Swift version
        run: swift --version

      - name: Build
        run: swift build -c release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TradeWithIt-${{ matrix.os }}
          path: .build/release/*
```

Workflow configuration (please complete the following information):

Action version (uses): swift-actions/setup-swift@v2
Platform (runs-on): windows-latest
Swift version (swift-version): 6.1
