### ISSUE TITLE
Swift Setup: Unexpected error, unable to continue

### ISSUE THREAD

**Issue by odrobnik** [swift-actions/setup-swift#739]
**Describe the bug**

```
Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
The process '/usr/bin/gpg' failed with exit code 2
Stacktrace:
Error: The process '/usr/bin/gpg' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/swift-actions/setup-swift/v2.2.0/dist/index.js:3195:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/swift-actions/setup-swift/v2.2.0/dist/index.js:3178:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/swift-actions/setup-swift/v2.2.0/dist/index.js:3072:27)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Workflow configuration (please complete the following information):**

The Linux build started failing, on `Setup Swift 6.0`, in this yml:

```

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift 6.0
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "6.0"

      - name: Verify Swift version
        run: swift --version
      
      - name: Build & Test
        run: swift test

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift 6.0
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "6.0"

      - name: Verify Swift version
        run: swift --version
      
      - name: Build & Test
        run: swift test 
```
